### ISSUE TITLE
luasocket for lua5.1

### ISSUE THREAD

**Issue by jlukovic** [fedepell/meta-lua#3]
Do you know which hash is for lua5.1? I need luasocket for lua5.1, not for 5.3.
Thanks!

**Comment by fedepell** [comment]
Hello,
Did you just try to change the
```
LUA_VERSION = "5.3"
```
to 5.1 ? At a fast look at the source it shouldn't be a problem to build also for 5.1, but I don't have right now an easy way to test it. But if you maybe have already the environment ready it could be fast! 

Cheers,
F.

**Comment by jlukovic** [comment]
Yes, I have tried, but that make folder /lua/5.1, and when i run my lua script, i get error: 
error loading module 'socket.core' from file '/usr/lib/lua/5.1/socket/core.so': /usr/lib/lua/5.1/socket/core.so: undefined symbol: luaL_
and i found that that error means i have wrong luasocket packet, for lua5.2 or lua5.3.

**Comment by fedepell** [comment]
But is the lua basic package on which this depends (`DEPENDS += "lua-native lua"`) 5.1 ? On top of which Yocto version are you building this against?

**Comment by jlukovic** [comment]
We solved the problem by changing some paths and depens is luajit, which is actually lua5.1. Thank you for responses!
